baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Yo-kai Watch TKB'
theme = 'hugo-geekdoc'

# Required to get well formatted code blocks
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
  tag = 'tags'

[params]
  [params.geekdocContentLicense]
    name = 'CC BY 4.0'
    link = 'https://creativecommons.org/licenses/by/4.0/'
